"""Added summary_text and created_at fields for VideoSessionSaveModel

Revision ID: a5bfc3f88de4
Revises: cc8d83c0a6ee
Create Date: 2026-07-11 21:07:12.251464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5bfc3f88de4'
down_revision = 'cc8d83c0a6ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('summary_text')

    # ### end Alembic commands ###
